name: backend-ci

on:
  push:
    branches: [ main, dev, development ]
    paths:
      - 'backend/**'
  pull_request:
    branches: [ main, dev, development ]
    paths:
      - 'backend/**'

jobs:
  build-backend:
    name: Build Backend
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - uses: actions/setup-node@v6
        with:
          node-version: '24'

      - name: Install dependencies
        run: npm ci
        working-directory: backend

      - name: Build (if present)
        run: npm run build --if-present
        working-directory: backend